//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservicemart.com/ws/", ConfigurationName="ServiceReference1.USZipSoap")]
    public interface USZipSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicemart.com/ws/ValidateZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ValidateZip(string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicemart.com/ws/ValidateZip", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ValidateZipAsync(string ZipCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface USZipSoapChannel : WebApp.ServiceReference1.USZipSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class USZipSoapClient : System.ServiceModel.ClientBase<WebApp.ServiceReference1.USZipSoap>, WebApp.ServiceReference1.USZipSoap {
        
        public USZipSoapClient() {
        }
        
        public USZipSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public USZipSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USZipSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USZipSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidateZip(string ZipCode) {
            return base.Channel.ValidateZip(ZipCode);
        }
        
        public System.Threading.Tasks.Task<string> ValidateZipAsync(string ZipCode) {
            return base.Channel.ValidateZipAsync(ZipCode);
        }
    }
}
